# Makefile.nvhbi -- B200 NV-HBI (die-to-die) bandwidth study.
#
#   make -f Makefile.nvhbi              # the three experiment binaries
#   make -f Makefile.nvhbi probes       # the topology / routing checker
#   make -f Makefile.nvhbi ARCH=100     # sm_100 = Blackwell (default)

NVCC  ?= nvcc
ARCH  ?= 100

NVCCFLAGS ?= -O3 -std=c++14 \
             -Xptxas -dlcm=ca -Xptxas -dscm=cg \
             -gencode arch=compute_$(ARCH),code=sm_$(ARCH)

BINS   := nvhbi_exp1_bisection nvhbi_dualdir nvhbi_exp23_peer
PROBES := nvhbi_route_probe

.PHONY: all probes clean

all: $(BINS)
probes: $(PROBES)

$(BINS) $(PROBES): %: %.cu nvhbi_common.cuh
	$(NVCC) $(NVCCFLAGS) -o $@ $<

clean:
	rm -f $(BINS) $(PROBES)
